export const dom = {
    formPage: document.getElementById("formPage"),
    askPage: document.getElementById("askPage"),
    successPage: document.getElementById("successPage"),
    footerTag: document.getElementById("footerTag"),
    askTitle: document.getElementById("askTitle"),
    successImg: document.getElementById("successImg"),
    successQuote: document.getElementById("successQuote"),
    signature: document.getElementById("signature"),
    topBubble: document.getElementById("topBubble"),
    noBtn: document.getElementById("noBtn"),
    yesBtn: document.getElementById("yesBtn"),
    generateBtn: document.getElementById("generateBtn"),
    statusText: document.getElementById("statusText"),
    fromNameInput: document.getElementById("fromNameInput"),
    toNameInput: document.getElementById("toNameInput"),
    quoteInput: document.getElementById("quoteInput"),
    photoInput: document.getElementById("photoInput"),
    quickShare: document.getElementById("quickShare"),
    quickShareInput: document.getElementById("quickShareInput"),
    quickShareCopyBtn: document.getElementById("quickShareCopyBtn"),
    confettiCanvas: document.getElementById("confetti"),
};
